let stringOne = " # # # # #";
let stringTwo = "# # # # # ";
console.log(stringOne);
console.log(stringTwo);
console.log(stringOne);
console.log(stringTwo);
console.log(stringOne);
console.log(stringTwo);
console.log(stringOne);
console.log(stringTwo);